# Generated by Django 4.2.1 on 2023-05-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=4)),
                ('current_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_elevators', to='elevator_control.floor')),
                ('serviced_floors', models.ManyToManyField(related_name='serviced_elevators', to='elevator_control.floor')),
                ('target_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_elevators', to='elevator_control.floor')),
            ],
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_control.floor')),
                ('serviced_elevators', models.ManyToManyField(to='elevator_control.elevator')),
            ],
        ),
    ]
