# Generated by Django 4.2.1 on 2023-05-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlpanel',
            name='serviced_elevators',
        ),
        migrations.AlterField(
            model_name='controlpanel',
            name='location_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_panels', to='elevator_control.floor'),
        ),
    ]
