# Generated by Django 4.2.1 on 2023-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_control', '0002_remove_controlpanel_serviced_elevators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
